# frozen_string_literal: true

name              'golang'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides custom resources to install Go and Go packages'
source_url        'https://github.com/sous-chefs/golang'
issues_url        'https://github.com/sous-chefs/golang/issues'
chef_version      '>= 17.5'
version           '7.0.0'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
