name             'golang'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs go programming language'
source_url       'https://github.com/sous-chefs/golang'
issues_url       'https://github.com/sous-chefs/golang/issues'
chef_version     '>= 15.3'
version          '5.0.1'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'amazon'
supports 'scientific'
supports 'oracle'

depends 'ark', '~> 5.0'
